;;;; fortran-format-tests.lisp
;;;;
;;;; Regression tests for the FORTRAN-FORMAT library, expressed as
;;;; rt:deftest forms. Each test that was previously a CHECK call in
;;;; a hand-rolled RUN-SMOKE-TESTS driver is now its own deftest.
;;;;
;;;; To run:
;;;;
;;;;   (asdf:load-system "fortran-format-tests")
;;;;   (rt:do-tests)
;;;;
;;;; Or, when integrated into the f2cl regression suite, the single
;;;; do-tests call in f2cl/tests will pick these up.
;;;;
;;;; Many of the float-output cases were generated by running
;;;; gfortran with the equivalent format and capturing the exact
;;;; bytes between angle-bracket delimiters. A handful expect CL's
;;;; rounding behavior (round-half-away-from-zero) rather than
;;;; gfortran's (banker's rounding); those are flagged in test
;;;; names with -cl-rounding.

(in-package #:fortran-format)

;;; --------------------------------------------------------------
;;; Output
;;; --------------------------------------------------------------

(rt:deftest fmt.write.i5
    (write-format "(I5)" 42)
  "   42")

(rt:deftest fmt.write.i5.3
    (write-format "(I5.3)" 42)
  "  042")

(rt:deftest fmt.write.i5-negative
    (write-format "(I5)" -7)
  "   -7")

(rt:deftest fmt.write.i3-overflow
    (write-format "(I3)" 12345)
  "***")

(rt:deftest fmt.write.f8.2
    (write-format "(F8.2)" 3.14159d0)
  "    3.14")

(rt:deftest fmt.write.i5-1x-f8.2
    (write-format "(I5,1X,F8.2)" 1 2.5d0)
  "    1     2.50")

(rt:deftest fmt.write.3i4
    (write-format "(3I4)" 1 22 333)
  "   1  22 333")

(rt:deftest fmt.write.2-i3-a3
    (write-format "(2(I3,A3))" 1 "ab" 2 "cd")
  "  1 ab  2 cd")

(rt:deftest fmt.write.quoted-literal
    (write-format "(I3,'/',I3)" 7 11)
  "  7/ 11")

(rt:deftest fmt.write.h-descriptor
    (write-format "(2H/=,I3)" 5)
  "/=  5")

;;; --------------------------------------------------------------
;;; Input
;;; --------------------------------------------------------------

(rt:deftest fmt.read.i5
    (read-format "(I5)" "   42")
  (42))

(rt:deftest fmt.read.3i5
    (read-format "(3I5)" "    1    2    3")
  (1 2 3))

(rt:deftest fmt.read.i5-negative
    (read-format "(I5)" "   -7")
  (-7))

(rt:deftest fmt.read.f8.3-with-decimal
    (read-format "(F8.3)" "  12.345")
  (12.345d0))

(rt:deftest fmt.read.f8.3-without-decimal
    ;; Fortran F-format inserts an implicit decimal point
    (read-format "(F8.3)" "   12345")
  (12.345d0))

(rt:deftest fmt.read.e-format
    (read-format "(E12.4)" "  0.3142E+01")
  (3.142d0))

(rt:deftest fmt.read.d-style-exponent
    (read-format "(E12.4)" "  0.3142D+01")
  (3.142d0))

(rt:deftest fmt.read.leading-skip
    (read-format "(2X,I3)" "   42")
  (42))

(rt:deftest fmt.read.a5
    (read-format "(A5)" "hello world")
  ("hello"))

(rt:deftest fmt.read.mixed
    (read-format "(I3,1X,F5.2,1X,A4)" "  1  2.50 abcd")
  (1 2.50d0 "abcd"))

(rt:deftest fmt.read.logical-t
    (read-format "(L4)" "   T")
  (t))

(rt:deftest fmt.read.logical-f
    (read-format "(L4)" ".FAL")
  (nil))

;;; --------------------------------------------------------------
;;; Reversion (output)
;;; gfortran ground truth is captured in reversion.f
;;; --------------------------------------------------------------

(rt:deftest fmt.write.reversion.i3-5-values
    (write-format "(I3)" 1 2 3 4 5)
  #.(format nil "  1~%  2~%  3~%  4~%  5"))

(rt:deftest fmt.write.reversion.3i3-7-values
    (write-format "(3I3)" 1 2 3 4 5 6 7)
  #.(format nil "  1  2  3~%  4  5  6~%  7"))

(rt:deftest fmt.write.reversion.mixed
    (write-format "(A,2(I3,A2))" "X" 1 "aa" 2 "bb" 3 "cc" 4 "dd")
  #.(format nil "X  1aa  2bb~%  3cc  4dd"))

(rt:deftest fmt.write.reversion.i5-inner
    (write-format "(I5,(2F6.2))" 99 1.1d0 2.2d0 3.3d0 4.4d0)
  #.(format nil "   99  1.10  2.20~%  3.30  4.40"))

;;; --------------------------------------------------------------
;;; Reversion (input)
;;; Input reversion needs :num-vals plus enough records.
;;; --------------------------------------------------------------

(rt:deftest fmt.read.reversion.i3-4-values
    (read-format "(I3)"
                 #.(format nil " 11~% 22~% 33~% 44")
                 :num-vals 4)
  (11 22 33 44))

(rt:deftest fmt.read.reversion.a1-2i3-whole-format
    ;; Reversion of "(A1,2I3)" with no inner group = the whole format.
    ;; So the second cycle reads A1 again (the leading space on record 2).
    (read-format "(A1,2I3)"
                 #.(format nil "X  1  2~%  3  4")
                 :num-vals 5)
  ("X" 1 2 " " 3))

(rt:deftest fmt.read.reversion.a1-inner-2i3
    ;; Reversion = (2I3), so the second cycle reads two integers
    ;; without consuming an A1 first.
    (read-format "(A1,(2I3))"
                 #.(format nil "X  1  2~%  3  4")
                 :num-vals 5)
  ("X" 1 2 3 4))

;;; --------------------------------------------------------------
;;; Float output (vs gfortran)
;;; --------------------------------------------------------------

;;; F format

(rt:deftest fmt.write.f.f8.2.pi
    (write-format "(F8.2)" 3.14159d0)
  "    3.14")

(rt:deftest fmt.write.f.f8.2.neg-pi
    (write-format "(F8.2)" -3.14159d0)
  "   -3.14")

(rt:deftest fmt.write.f.f8.2.zero
    (write-format "(F8.2)" 0.0d0)
  "    0.00")

(rt:deftest fmt.write.f.f8.2.big
    (write-format "(F8.2)" 12345.67d0)
  "12345.67")

(rt:deftest fmt.write.f.f8.2.overflow
    (write-format "(F8.2)" 123456.78d0)
  "********")

(rt:deftest fmt.write.f.f8.2.round-up
    (write-format "(F8.2)" 0.005d0)
  "    0.01")

(rt:deftest fmt.write.f.f8.2.round-down
    (write-format "(F8.2)" 0.004d0)
  "    0.00")

(rt:deftest fmt.write.f.f8.4.fraction
    (write-format "(F8.4)" 0.123456789d0)
  "  0.1235")

(rt:deftest fmt.write.f.f10.0.int-like
    (write-format "(F10.0)" 1234567.0d0)
  "  1234567.")

(rt:deftest fmt.write.f.f10.6.zero
    (write-format "(F10.6)" 0.0d0)
  "  0.000000")

(rt:deftest fmt.write.f.f5.2.overflow
    (write-format "(F5.2)" 12345.67d0)
  "*****")

;;; E format

(rt:deftest fmt.write.e.e12.4.pi
    (write-format "(E12.4)" 3.14159d0)
  "  0.3142E+01")

(rt:deftest fmt.write.e.e12.4.neg-pi
    (write-format "(E12.4)" -3.14159d0)
  " -0.3142E+01")

(rt:deftest fmt.write.e.e12.4.zero
    (write-format "(E12.4)" 0.0d0)
  "  0.0000E+00")

(rt:deftest fmt.write.e.e12.4.1234.5-cl-rounding
    ;; gfortran (banker's rounding) produces "  0.1234E+04". CL's ~E
    ;; rounding mode is implementation-defined: SBCL rounds half-to-even
    ;; (matches gfortran here), CMUCL rounds half-away-from-zero (gives
    ;; "...1235..."). Accept both until the bit-exact normalize-float
    ;; path is restored.
    (not (null (member (write-format "(E12.4)" 1234.5d0)
                       '("  0.1234E+04" "  0.1235E+04")
                       :test #'string=)))
  t)

(rt:deftest fmt.write.e.e12.4.tiny
    (write-format "(E12.4)" 0.0001234d0)
  "  0.1234E-03")

(rt:deftest fmt.write.e.e14.6.avogadro
    (write-format "(E14.6)" 6.022d23)
  "  0.602200E+24")

(rt:deftest fmt.write.e.e14.6.electron-charge
    (write-format "(E14.6)" 1.6d-19)
  "  0.160000E-18")

(rt:deftest fmt.write.e.e16.6e3.tiny
    (write-format "(E16.6E3)" 1.6d-119)
  "   0.160000E-118")

(rt:deftest fmt.write.e.e10.4.too-narrow
    ;; Three-digit exponent doesn't fit -- letter is dropped
    (write-format "(E10.4)" 1.234d100)
  "0.1234+101")

;;; ES format

(rt:deftest fmt.write.es.es12.4.pi
    (write-format "(ES12.4)" 3.14159d0)
  "  3.1416E+00")

(rt:deftest fmt.write.es.es12.4.1234.5
    (write-format "(ES12.4)" 1234.5d0)
  "  1.2345E+03")

(rt:deftest fmt.write.es.es12.4.tiny
    (write-format "(ES12.4)" 0.0001234d0)
  "  1.2340E-04")

(rt:deftest fmt.write.es.es12.4.zero
    (write-format "(ES12.4)" 0.0d0)
  "  0.0000E+00")

;;; EN format

(rt:deftest fmt.write.en.en15.4.pi
    (write-format "(EN15.4)" 3.14159d0)
  "     3.1416E+00")

(rt:deftest fmt.write.en.en15.4.1234.5
    (write-format "(EN15.4)" 1234.5d0)
  "     1.2345E+03")

(rt:deftest fmt.write.en.en15.4.12345.6
    (write-format "(EN15.4)" 12345.6d0)
  "    12.3456E+03")

(rt:deftest fmt.write.en.en15.4.1234567.8
    (write-format "(EN15.4)" 1234567.8d0)
  "     1.2346E+06")

(rt:deftest fmt.write.en.en15.4.small
    (write-format "(EN15.4)" 0.001234d0)
  "     1.2340E-03")

(rt:deftest fmt.write.en.en15.4.zero
    (write-format "(EN15.4)" 0.0d0)
  "     0.0000E+00")

;;; G format

(rt:deftest fmt.write.g.g12.4.pi
    (write-format "(G12.4)" 3.14159d0)
  "   3.142    ")

(rt:deftest fmt.write.g.g12.4.small
    (write-format "(G12.4)" 0.00314d0)
  "  0.3140E-02")

(rt:deftest fmt.write.g.g12.4.large
    (write-format "(G12.4)" 314159.0d0)
  "  0.3142E+06")

(rt:deftest fmt.write.g.g12.4.1234.5-cl-rounding
    ;; CL rounds 1234.5 to 1235 (round-half-away-from-zero);
    ;; gfortran would produce "   1234.    " (banker's rounding).
    (write-format "(G12.4)" 1234.5d0)
  "   1235.    ")

(rt:deftest fmt.write.g.g12.4.zero
    (write-format "(G12.4)" 0.0d0)
  "   0.000    ")

;;; --------------------------------------------------------------
;;; Float edge cases (vs gfortran)
;;; --------------------------------------------------------------

(rt:deftest fmt.write.f.f6.3.99.9995
    ;; Not a tie -- rounds down, doesn't carry to 100.000
    (write-format "(F6.3)" 99.9995d0)
  "99.999")

(rt:deftest fmt.write.f.f8.3.negative-zero
    (write-format "(F8.3)" -0.0d0)
  "  -0.000")

(rt:deftest fmt.write.f.f6.3.carry
    ;; 0.9995 rounds up to 1.000 -- carry across the decimal
    (write-format "(F6.3)" 0.9995d0)
  " 1.000")

(rt:deftest fmt.write.e.e10.3.0.0001
    (write-format "(E10.3)" 0.0001d0)
  " 0.100E-03")

(rt:deftest fmt.write.f.f6.2.underflow
    (write-format "(F6.2)" 1.0d-10)
  "  0.00")

(rt:deftest fmt.write.f.f6.0.overflow
    (write-format "(F6.0)" 1.0d10)
  "******")

(rt:deftest fmt.write.es.es10.2.zero
    (write-format "(ES10.2)" 0.0d0)
  "  0.00E+00")
