;;;; fortran-format-tests.lisp
;;;;
;;;; Regression tests for the FORTRAN-FORMAT library, expressed as
;;;; rt:deftest forms. Each test that was previously a CHECK call in
;;;; a hand-rolled RUN-SMOKE-TESTS driver is now its own deftest.
;;;;
;;;; To run:
;;;;
;;;;   (asdf:load-system "fortran-format-tests")
;;;;   (rt:do-tests)
;;;;
;;;; Or, when integrated into the f2cl regression suite, the single
;;;; do-tests call in f2cl/tests will pick these up.
;;;;
;;;; Many of the float-output cases were generated by running
;;;; gfortran with the equivalent format and capturing the exact
;;;; bytes between angle-bracket delimiters. A handful expect CL's
;;;; rounding behavior (round-half-away-from-zero) rather than
;;;; gfortran's (banker's rounding); those are flagged in test
;;;; names with -cl-rounding.

(in-package #:fortran-format)

;;; --------------------------------------------------------------
;;; Output
;;; --------------------------------------------------------------

(rt:deftest fmt.write.i5
    (write-format "(I5)" 42)
  "   42")

(rt:deftest fmt.write.i5.3
    (write-format "(I5.3)" 42)
  "  042")

(rt:deftest fmt.write.i5-negative
    (write-format "(I5)" -7)
  "   -7")

(rt:deftest fmt.write.i3-overflow
    (write-format "(I3)" 12345)
  "***")

(rt:deftest fmt.write.f8.2
    (write-format "(F8.2)" 3.14159d0)
  "    3.14")

(rt:deftest fmt.write.i5-1x-f8.2
    (write-format "(I5,1X,F8.2)" 1 2.5d0)
  "    1     2.50")

(rt:deftest fmt.write.3i4
    (write-format "(3I4)" 1 22 333)
  "   1  22 333")

(rt:deftest fmt.write.2-i3-a3
    (write-format "(2(I3,A3))" 1 "ab" 2 "cd")
  "  1 ab  2 cd")

(rt:deftest fmt.write.quoted-literal
    (write-format "(I3,'/',I3)" 7 11)
  "  7/ 11")

(rt:deftest fmt.write.h-descriptor
    (write-format "(2H/=,I3)" 5)
  "/=  5")

;;; --------------------------------------------------------------
;;; Logical output
;;; --------------------------------------------------------------

(rt:deftest fmt.write.l4-true
    (write-format "(L4)" t)
  "   T")

(rt:deftest fmt.write.l4-false
    (write-format "(L4)" nil)
  "   F")

(rt:deftest fmt.write.l1-true
    (write-format "(L1)" t)
  "T")

;;; --------------------------------------------------------------
;;; BOZ output (binary, octal, hex)
;;; --------------------------------------------------------------

(rt:deftest fmt.write.b8-13
    (write-format "(B8)" 13)
  "    1101")

(rt:deftest fmt.write.o8-13
    (write-format "(O8)" 13)
  "      15")

(rt:deftest fmt.write.z8-255
    (write-format "(Z8)" 255)
  "      FF")

(rt:deftest fmt.write.z8-10
    ;; Hex digits A-F come out uppercase.
    (write-format "(Z8)" 10)
  "       A")

(rt:deftest fmt.write.z4-fits-exactly
    (write-format "(Z4)" 65535)
  "FFFF")

(rt:deftest fmt.write.b8.5-min-digits
    ;; Min-digits zero-pads in the chosen base.
    (write-format "(B8.5)" 5)
  "   00101")

;;; --------------------------------------------------------------
;;; Sign control SP/SS/S
;;; --------------------------------------------------------------

(rt:deftest fmt.write.sp-i5-positive
    (write-format "(SP,I5)" 42)
  "  +42")

(rt:deftest fmt.write.sp-i5-negative
    ;; Negatives always show '-' regardless of SP/SS state.
    (write-format "(SP,I5)" -7)
  "   -7")

(rt:deftest fmt.write.sp-i5-zero
    (write-format "(SP,I5)" 0)
  "   +0")

(rt:deftest fmt.write.ss-i5
    ;; SS suppresses the optional plus -- same as default.
    (write-format "(SS,I5)" 42)
  "   42")

(rt:deftest fmt.write.sp-then-ss
    ;; Later SS overrides earlier SP within the same format.
    (write-format "(SP,SS,I5)" 42)
  "   42")

(rt:deftest fmt.write.sp-then-i-then-ss-then-i
    ;; The flag affects only the integers emitted while it is in effect.
    (write-format "(SP,I5,SS,I5)" 42 42)
  "  +42   42")

(rt:deftest fmt.write.s-restores-default
    ;; S restores processor default (same as SS in our implementation).
    (write-format "(S,I5)" 42)
  "   42")

(rt:deftest fmt.write.sp-f8.2
    (write-format "(SP,F8.2)" 3.14d0)
  "   +3.14")

(rt:deftest fmt.write.sp-e12.4
    (write-format "(SP,E12.4)" 3.14d0)
  " +0.3140E+01")

(rt:deftest fmt.write.sp-does-not-apply-to-boz
    ;; gfortran behavior: BOZ output is an unsigned bit-pattern and
    ;; carries no sign even under SP.
    (write-format "(SP,Z4)" 10)
  "   A")

(rt:deftest fmt.write.sp-does-not-leak-between-calls
    ;; *INCLUDE-PLUS* must be bound fresh on each WRITE-FORMAT call.
    (progn (write-format "(SP,I5)" 42)
           (write-format "(I5)" 42))
  "   42")

;;; --------------------------------------------------------------
;;; Scale factor (kP)
;;; --------------------------------------------------------------

;; On F: rescale the value by 10^k.

(rt:deftest fmt.write.1p-f8.2
    (write-format "(1P,F8.2)" 3.14159d0)
  "   31.42")

(rt:deftest fmt.write.2p-f8.2
    (write-format "(2P,F8.2)" 3.14159d0)
  "  314.16")

(rt:deftest fmt.write.3p-f8.2
    (write-format "(3P,F8.2)" 3.14159d0)
  " 3141.59")

(rt:deftest fmt.write.neg1p-f8.2
    (write-format "(-1P,F8.2)" 3.14159d0)
  "    0.31")

(rt:deftest fmt.write.neg2p-f8.2
    (write-format "(-2P,F8.2)" 3.14159d0)
  "    0.03")

;; On E: digit shuffle between mantissa and exponent.

(rt:deftest fmt.write.1p-e12.4
    (write-format "(1P,E12.4)" 3.14159d0)
  "  3.1416E+00")

(rt:deftest fmt.write.2p-e12.4
    (write-format "(2P,E12.4)" 3.14159d0)
  "  31.416E-01")

(rt:deftest fmt.write.3p-e12.4
    (write-format "(3P,E12.4)" 3.14159d0)
  "  314.16E-02")

(rt:deftest fmt.write.neg1p-e12.4
    (write-format "(-1P,E12.4)" 3.14159d0)
  "  0.0314E+02")

(rt:deftest fmt.write.neg2p-e12.4
    (write-format "(-2P,E12.4)" 3.14159d0)
  "  0.0031E+03")

;; ES and EN ignore the scale factor.

(rt:deftest fmt.write.1p-es12.4-ignored
    (write-format "(1P,ES12.4)" 3.14159d0)
  "  3.1416E+00")

(rt:deftest fmt.write.2p-es12.4-ignored
    (write-format "(2P,ES12.4)" 3.14159d0)
  "  3.1416E+00")

(rt:deftest fmt.write.1p-en15.6-ignored
    (write-format "(1P,EN15.6)" 3.14159d0)
  "   3.141590E+00")

;; G in E mode honors scale; in F mode it doesn't.

(rt:deftest fmt.write.1p-g12.4-e-mode-small
    ;; 0.001 is below 0.1 so G picks E mode; 1P applies.
    (write-format "(1P,G12.4)" 0.001d0)
  "  1.0000E-03")

(rt:deftest fmt.write.1p-g12.4-e-mode-big
    ;; 1e6 is >= 10^4 so G picks E mode; 1P applies.
    (write-format "(1P,G12.4)" 1.0d6)
  "  1.0000E+06")

;; Scale persists through subsequent descriptors in the same call.

(rt:deftest fmt.write.scale-persists
    (write-format "(1P,F8.2,F8.2)" 3.14159d0 3.14159d0)
  "   31.42   31.42")

;; 0P resets the scale.

(rt:deftest fmt.write.0p-resets-scale
    (write-format "(1P,F8.2,0P,F8.2)" 3.14159d0 3.14159d0)
  "   31.42    3.14")

;; Scale does not affect integer or BOZ output.

(rt:deftest fmt.write.1p-i5-unaffected
    (write-format "(1P,I5)" 42)
  "   42")

(rt:deftest fmt.write.1p-z4-unaffected
    (write-format "(1P,Z4)" 10)
  "   A")

;; Scale state must not leak between WRITE-FORMAT calls.

(rt:deftest fmt.write.scale-does-not-leak-between-calls
    (progn (write-format "(1P,F8.2)" 3.14d0)
           (write-format "(F8.2)" 3.14d0))
  "    3.14")

;;; --------------------------------------------------------------
;;; T / TR positioning (forward only)
;;;
;;; T n jumps to absolute 1-based column n; TR n advances n columns.
;;; Backward T (target column < current) and TL are not supported
;;; in this implementation -- both signal invalid-format.  A full
;;; mutable-record buffer would be required to support them, and
;;; backward T isn't used in any of the f2cl-translated packages
;;; (BLAS, LAPACK, ODEPACK, QUADPACK, MINPACK, ...).
;;; --------------------------------------------------------------

(rt:deftest fmt.write.t5-a3
    (write-format "(T5,A3)" "abc")
  "    abc")

(rt:deftest fmt.write.t1-a3
    ;; T1 from column 1 is a no-op forward jump.
    (write-format "(T1,A3)" "abc")
  "abc")

(rt:deftest fmt.write.t5-i3
    (write-format "(T5,I3)" 1)
  "      1")

(rt:deftest fmt.write.a-t20-a
    (write-format "(A,T20,A)" "abc" "Z")
  "abc                Z")

(rt:deftest fmt.write.a-t4-a-adjacent
    ;; T4 lands exactly at the next column with no gap to fill.
    (write-format "(A,T4,A)" "abc" "X")
  "abcX")

(rt:deftest fmt.write.tr-with-spaces
    (write-format "(A,TR3,A)" "abc" "def")
  "abc   def")

(rt:deftest fmt.write.tr5-a1
    (write-format "(TR5,A1)" "Q")
  "     Q")

(rt:deftest fmt.write.t-tracks-column-after-multiple
    ;; Column counter must follow earlier writes.  After "  1  2"
    ;; *column* is 7, then T15 jumps to column 15.
    (write-format "(I3,I3,T15,A)" 1 2 "Z")
  "  1  2        Z")

(rt:deftest fmt.write.backward-t-errors
    ;; T1 after writing "abc" would have to overwrite -- we refuse.
    (handler-case (write-format "(A3,T1,A3)" "abc" "def")
      (invalid-format () :rejected))
  :rejected)

(rt:deftest fmt.write.tl-errors
    (handler-case (write-format "(A,TL2,A)" "abc" "X")
      (invalid-format () :rejected))
  :rejected)

(rt:deftest fmt.write.t-does-not-leak-between-calls
    (progn (write-format "(T5,A)" "X")
           (write-format "(A)" "Q"))
  "Q")

;;; --------------------------------------------------------------
;;; / (slash) on output
;;;
;;; Slash terminates the current record and starts a new one;
;;; *column* resets to 1.
;;; --------------------------------------------------------------

(rt:deftest fmt.write.slash-between-strings
    (write-format "(A,/,A)" "abc" "def")
  #.(format nil "abc~%def"))

(rt:deftest fmt.write.slash-between-integers
    (write-format "(I3,/,I3)" 1 2)
  #.(format nil "  1~%  2"))

(rt:deftest fmt.write.slash-resets-column
    ;; T5 after the slash works from column 1 of the new record.
    (write-format "(A,/,T5,A)" "abc" "def")
  #.(format nil "abc~%    def"))

;;; --------------------------------------------------------------
;;; Input
;;; --------------------------------------------------------------

(rt:deftest fmt.read.i5
    (read-format "(I5)" "   42")
  (42))

(rt:deftest fmt.read.3i5
    (read-format "(3I5)" "    1    2    3")
  (1 2 3))

(rt:deftest fmt.read.i5-negative
    (read-format "(I5)" "   -7")
  (-7))

(rt:deftest fmt.read.f8.3-with-decimal
    (read-format "(F8.3)" "  12.345")
  (12.345d0))

(rt:deftest fmt.read.f8.3-without-decimal
    ;; Fortran F-format inserts an implicit decimal point
    (read-format "(F8.3)" "   12345")
  (12.345d0))

(rt:deftest fmt.read.e-format
    (read-format "(E12.4)" "  0.3142E+01")
  (3.142d0))

(rt:deftest fmt.read.d-style-exponent
    (read-format "(E12.4)" "  0.3142D+01")
  (3.142d0))

(rt:deftest fmt.read.leading-skip
    (read-format "(2X,I3)" "   42")
  (42))

(rt:deftest fmt.read.a5
    (read-format "(A5)" "hello world")
  ("hello"))

(rt:deftest fmt.read.mixed
    (read-format "(I3,1X,F5.2,1X,A4)" "  1  2.50 abcd")
  (1 2.50d0 "abcd"))

(rt:deftest fmt.read.logical-t
    (read-format "(L4)" "   T")
  (t))

(rt:deftest fmt.read.logical-f
    (read-format "(L4)" ".FAL")
  (nil))

;;; --------------------------------------------------------------
;;; Reversion (output)
;;; gfortran ground truth is captured in reversion.f
;;; --------------------------------------------------------------

(rt:deftest fmt.write.reversion.i3-5-values
    (write-format "(I3)" 1 2 3 4 5)
  #.(format nil "  1~%  2~%  3~%  4~%  5"))

(rt:deftest fmt.write.reversion.3i3-7-values
    (write-format "(3I3)" 1 2 3 4 5 6 7)
  #.(format nil "  1  2  3~%  4  5  6~%  7"))

(rt:deftest fmt.write.reversion.mixed
    (write-format "(A,2(I3,A2))" "X" 1 "aa" 2 "bb" 3 "cc" 4 "dd")
  #.(format nil "X  1aa  2bb~%  3cc  4dd"))

(rt:deftest fmt.write.reversion.i5-inner
    (write-format "(I5,(2F6.2))" 99 1.1d0 2.2d0 3.3d0 4.4d0)
  #.(format nil "   99  1.10  2.20~%  3.30  4.40"))

;;; --------------------------------------------------------------
;;; Reversion (input)
;;; Input reversion needs :num-vals plus enough records.
;;; --------------------------------------------------------------

(rt:deftest fmt.read.reversion.i3-4-values
    (read-format "(I3)"
                 #.(format nil " 11~% 22~% 33~% 44")
                 :num-vals 4)
  (11 22 33 44))

(rt:deftest fmt.read.reversion.a1-2i3-whole-format
    ;; Reversion of "(A1,2I3)" with no inner group = the whole format.
    ;; So the second cycle reads A1 again (the leading space on record 2).
    (read-format "(A1,2I3)"
                 #.(format nil "X  1  2~%  3  4")
                 :num-vals 5)
  ("X" 1 2 " " 3))

(rt:deftest fmt.read.reversion.a1-inner-2i3
    ;; Reversion = (2I3), so the second cycle reads two integers
    ;; without consuming an A1 first.
    (read-format "(A1,(2I3))"
                 #.(format nil "X  1  2~%  3  4")
                 :num-vals 5)
  ("X" 1 2 3 4))

;;; --------------------------------------------------------------
;;; Float output (vs gfortran)
;;; --------------------------------------------------------------

;;; F format

(rt:deftest fmt.write.f.f8.2.pi
    (write-format "(F8.2)" 3.14159d0)
  "    3.14")

(rt:deftest fmt.write.f.f8.2.neg-pi
    (write-format "(F8.2)" -3.14159d0)
  "   -3.14")

(rt:deftest fmt.write.f.f8.2.zero
    (write-format "(F8.2)" 0.0d0)
  "    0.00")

(rt:deftest fmt.write.f.f8.2.big
    (write-format "(F8.2)" 12345.67d0)
  "12345.67")

(rt:deftest fmt.write.f.f8.2.overflow
    (write-format "(F8.2)" 123456.78d0)
  "********")

(rt:deftest fmt.write.f.f8.2.round-up
    (write-format "(F8.2)" 0.005d0)
  "    0.01")

(rt:deftest fmt.write.f.f8.2.round-down
    (write-format "(F8.2)" 0.004d0)
  "    0.00")

(rt:deftest fmt.write.f.f8.4.fraction
    (write-format "(F8.4)" 0.123456789d0)
  "  0.1235")

(rt:deftest fmt.write.f.f10.0.int-like
    (write-format "(F10.0)" 1234567.0d0)
  "  1234567.")

(rt:deftest fmt.write.f.f10.6.zero
    (write-format "(F10.6)" 0.0d0)
  "  0.000000")

(rt:deftest fmt.write.f.f5.2.overflow
    (write-format "(F5.2)" 12345.67d0)
  "*****")

;;; E format

(rt:deftest fmt.write.e.e12.4.pi
    (write-format "(E12.4)" 3.14159d0)
  "  0.3142E+01")

(rt:deftest fmt.write.e.e12.4.neg-pi
    (write-format "(E12.4)" -3.14159d0)
  " -0.3142E+01")

(rt:deftest fmt.write.e.e12.4.zero
    (write-format "(E12.4)" 0.0d0)
  "  0.0000E+00")

(rt:deftest fmt.write.e.e12.4.1234.5-cl-rounding
    ;; gfortran (banker's rounding) produces "  0.1234E+04". CL's ~E
    ;; rounding mode is implementation-defined: SBCL rounds half-to-even
    ;; (matches gfortran here), CMUCL rounds half-away-from-zero (gives
    ;; "...1235..."). Accept both until the bit-exact normalize-float
    ;; path is restored.
    (not (null (member (write-format "(E12.4)" 1234.5d0)
                       '("  0.1234E+04" "  0.1235E+04")
                       :test #'string=)))
  t)

(rt:deftest fmt.write.e.e12.4.tiny
    (write-format "(E12.4)" 0.0001234d0)
  "  0.1234E-03")

(rt:deftest fmt.write.e.e14.6.avogadro
    (write-format "(E14.6)" 6.022d23)
  "  0.602200E+24")

(rt:deftest fmt.write.e.e14.6.electron-charge
    (write-format "(E14.6)" 1.6d-19)
  "  0.160000E-18")

(rt:deftest fmt.write.e.e16.6e3.tiny
    (write-format "(E16.6E3)" 1.6d-119)
  "   0.160000E-118")

(rt:deftest fmt.write.e.e10.4.too-narrow
    ;; Three-digit exponent doesn't fit -- letter is dropped
    (write-format "(E10.4)" 1.234d100)
  "0.1234+101")

;;; ES format

(rt:deftest fmt.write.es.es12.4.pi
    (write-format "(ES12.4)" 3.14159d0)
  "  3.1416E+00")

(rt:deftest fmt.write.es.es12.4.1234.5
    (write-format "(ES12.4)" 1234.5d0)
  "  1.2345E+03")

(rt:deftest fmt.write.es.es12.4.tiny
    (write-format "(ES12.4)" 0.0001234d0)
  "  1.2340E-04")

(rt:deftest fmt.write.es.es12.4.zero
    (write-format "(ES12.4)" 0.0d0)
  "  0.0000E+00")

;;; EN format

(rt:deftest fmt.write.en.en15.4.pi
    (write-format "(EN15.4)" 3.14159d0)
  "     3.1416E+00")

(rt:deftest fmt.write.en.en15.4.1234.5
    (write-format "(EN15.4)" 1234.5d0)
  "     1.2345E+03")

(rt:deftest fmt.write.en.en15.4.12345.6
    (write-format "(EN15.4)" 12345.6d0)
  "    12.3456E+03")

(rt:deftest fmt.write.en.en15.4.1234567.8
    (write-format "(EN15.4)" 1234567.8d0)
  "     1.2346E+06")

(rt:deftest fmt.write.en.en15.4.small
    (write-format "(EN15.4)" 0.001234d0)
  "     1.2340E-03")

(rt:deftest fmt.write.en.en15.4.zero
    (write-format "(EN15.4)" 0.0d0)
  "     0.0000E+00")

;;; G format

(rt:deftest fmt.write.g.g12.4.pi
    (write-format "(G12.4)" 3.14159d0)
  "   3.142    ")

(rt:deftest fmt.write.g.g12.4.small
    (write-format "(G12.4)" 0.00314d0)
  "  0.3140E-02")

(rt:deftest fmt.write.g.g12.4.large
    (write-format "(G12.4)" 314159.0d0)
  "  0.3142E+06")

(rt:deftest fmt.write.g.g12.4.1234.5-cl-rounding
    ;; CL rounds 1234.5 to 1235 (round-half-away-from-zero);
    ;; gfortran would produce "   1234.    " (banker's rounding).
    (write-format "(G12.4)" 1234.5d0)
  "   1235.    ")

(rt:deftest fmt.write.g.g12.4.zero
    (write-format "(G12.4)" 0.0d0)
  "   0.000    ")

;;; --------------------------------------------------------------
;;; Float edge cases (vs gfortran)
;;; --------------------------------------------------------------

(rt:deftest fmt.write.f.f6.3.99.9995
    ;; Not a tie -- rounds down, doesn't carry to 100.000
    (write-format "(F6.3)" 99.9995d0)
  "99.999")

(rt:deftest fmt.write.f.f8.3.negative-zero
    (write-format "(F8.3)" -0.0d0)
  "  -0.000")

(rt:deftest fmt.write.f.f6.3.carry
    ;; 0.9995 rounds up to 1.000 -- carry across the decimal
    (write-format "(F6.3)" 0.9995d0)
  " 1.000")

(rt:deftest fmt.write.e.e10.3.0.0001
    (write-format "(E10.3)" 0.0001d0)
  " 0.100E-03")

(rt:deftest fmt.write.f.f6.2.underflow
    (write-format "(F6.2)" 1.0d-10)
  "  0.00")

(rt:deftest fmt.write.f.f6.0.overflow
    (write-format "(F6.0)" 1.0d10)
  "******")

(rt:deftest fmt.write.es.es10.2.zero
    (write-format "(ES10.2)" 0.0d0)
  "  0.00E+00")
