;;;; fortran-format-tests.lisp
;;;;
;;;; Smoke tests covering output, input, reversion, and floating-
;;;; point formatting. Run with
;;;;
;;;;   (fortran-format::run-smoke-tests)
;;;;
;;;; Returns T if all tests pass, NIL otherwise. Prints each test
;;;; case with its got/expected values.
;;;;
;;;; Many of the float-output cases were generated by running
;;;; gfortran with the equivalent format and capturing the exact
;;;; bytes between angle-bracket delimiters. A handful expect CL's
;;;; rounding behavior (round-half-away-from-zero) rather than
;;;; gfortran's (banker's rounding); those are flagged in the test
;;;; labels.

(in-package #:fortran-format)

;;; ---------------------------------------------------------------
;;; Smoke tests
;;; ---------------------------------------------------------------

(defun run-smoke-tests ()
  (let ((failures 0))
    (flet ((check (label got expected &key (test #'equal))
             (let ((ok (funcall test got expected)))
               (unless ok (incf failures))
               (format t "~A:~%  got      ~S~%  expected ~S~%  ~A~%~%"
                       label got expected (if ok "OK" "MISMATCH")))))
      (format t "===== OUTPUT =====~%~%")
      (check "I5"
             (write-format "(I5)" 42) "   42")
      (check "I5.3"
             (write-format "(I5.3)" 42) "  042")
      (check "I5 negative"
             (write-format "(I5)" -7) "   -7")
      (check "I3 overflow"
             (write-format "(I3)" 12345) "***")
      (check "F8.2"
             (write-format "(F8.2)" 3.14159d0) "    3.14")
      (check "(I5,1X,F8.2)"
             (write-format "(I5,1X,F8.2)" 1 2.5d0) "    1     2.50")
      (check "3I4"
             (write-format "(3I4)" 1 22 333) "   1  22 333")
      (check "(2(I3,A3))"
             (write-format "(2(I3,A3))" 1 "ab" 2 "cd") "  1 ab  2 cd")
      (check "quoted literal"
             (write-format "(I3,'/',I3)" 7 11) "  7/ 11")
      (check "H descriptor"
             (write-format "(2H/=,I3)" 5) "/=  5")

      (format t "===== INPUT =====~%~%")
      (check "read I5"
             (read-format "(I5)" "   42") '(42))
      (check "read 3I5"
             (read-format "(3I5)" "    1    2    3") '(1 2 3))
      (check "read I5 negative"
             (read-format "(I5)" "   -7") '(-7))
      (check "read F8.3 with decimal"
             (read-format "(F8.3)" "  12.345") '(12.345d0))
      (check "read F8.3 without decimal"   ; Fortran F-format inserts implicit decimal
             (read-format "(F8.3)" "   12345") '(12.345d0))
      (check "read E format"
             (read-format "(E12.4)" "  0.3142E+01") '(3.142d0))
      (check "read D-style exponent"
             (read-format "(E12.4)" "  0.3142D+01") '(3.142d0))
      (check "read with leading skip"
             (read-format "(2X,I3)" "   42") '(42))
      (check "read A5"
             (read-format "(A5)" "hello world") '("hello"))
      (check "read mixed"
             (read-format "(I3,1X,F5.2,1X,A4)" "  1  2.50 abcd") '(1 2.50d0 "abcd"))
      (check "read logical T"
             (read-format "(L4)" "   T") '(t))
      (check "read logical F (.FALSE.)"
             (read-format "(L4)" ".FAL") '(nil))

      (format t "===== REVERSION (OUTPUT) =====~%~%")
      ;; gfortran ground truth for these is captured in reversion.f
      (check "(I3) with 5 values"
             (write-format "(I3)" 1 2 3 4 5)
             (format nil "  1~%  2~%  3~%  4~%  5"))
      (check "(3I3) with 7 values"
             (write-format "(3I3)" 1 2 3 4 5 6 7)
             (format nil "  1  2  3~%  4  5  6~%  7"))
      (check "(A,2(I3,A2)) with mixed list"
             (write-format "(A,2(I3,A2))" "X" 1 "aa" 2 "bb" 3 "cc" 4 "dd")
             (format nil "X  1aa  2bb~%  3cc  4dd"))
      (check "(I5,(2F6.2)) with 5 values"
             (write-format "(I5,(2F6.2))" 99 1.1d0 2.2d0 3.3d0 4.4d0)
             (format nil "   99  1.10  2.20~%  3.30  4.40"))

      (format t "===== REVERSION (INPUT) =====~%~%")
      ;; Input reversion needs num-vals plus enough records.
      (check "(I3) reading 4 values across 4 records"
             (read-format "(I3)"
                          (format nil " 11~% 22~% 33~% 44")
                          :num-vals 4)
             '(11 22 33 44))
      (check "(A1,2I3) reads A1 + two ints then reverts to whole format"
             ;; Reversion of "(A1,2I3)" with no inner group = the whole format.
             ;; So the second cycle reads A1 again (the leading space on record 2).
             (read-format "(A1,2I3)"
                          (format nil "X  1  2~%  3  4")
                          :num-vals 5)
             '("X" 1 2 " " 3))
      (check "(A1,(2I3)) reverts to inner group only"
             ;; Reversion now = (2I3), so the second cycle reads two integers
             ;; without consuming an A1 first.
             (read-format "(A1,(2I3))"
                          (format nil "X  1  2~%  3  4")
                          :num-vals 5)
             '("X" 1 2 3 4))

      (format t "===== FLOAT OUTPUT (vs gfortran) =====~%~%")
      ;; F format
      (check "F8.2 / 3.14159"     (write-format "(F8.2)"  3.14159d0)    "    3.14")
      (check "F8.2 / -3.14159"    (write-format "(F8.2)" -3.14159d0)    "   -3.14")
      (check "F8.2 / 0.0"         (write-format "(F8.2)"  0.0d0)        "    0.00")
      (check "F8.2 / 12345.67"    (write-format "(F8.2)"  12345.67d0)   "12345.67")
      (check "F8.2 overflow"      (write-format "(F8.2)"  123456.78d0)  "********")
      (check "F8.2 / 0.005 (round up)" (write-format "(F8.2)" 0.005d0)  "    0.01")
      (check "F8.2 / 0.004 (round down)" (write-format "(F8.2)" 0.004d0) "    0.00")
      (check "F8.4 / 0.123456789" (write-format "(F8.4)" 0.123456789d0) "  0.1235")
      (check "F10.0 / 1234567.0"  (write-format "(F10.0)" 1234567.0d0)  "  1234567.")
      (check "F10.6 / 0.0"        (write-format "(F10.6)" 0.0d0)        "  0.000000")
      (check "F5.2 overflow"      (write-format "(F5.2)" 12345.67d0)    "*****")
      ;; E format
      (check "E12.4 / 3.14159"    (write-format "(E12.4)" 3.14159d0)    "  0.3142E+01")
      (check "E12.4 / -3.14159"   (write-format "(E12.4)" -3.14159d0)   " -0.3142E+01")
      (check "E12.4 / 0.0"        (write-format "(E12.4)" 0.0d0)        "  0.0000E+00")
      (check "E12.4 / 1234.5"     (write-format "(E12.4)" 1234.5d0)     "  0.1234E+04")
      (check "E12.4 / 0.0001234"  (write-format "(E12.4)" 0.0001234d0)  "  0.1234E-03")
      (check "E14.6 / 6.022e23"   (write-format "(E14.6)" 6.022d23)     "  0.602200E+24")
      (check "E14.6 / 1.6e-19"    (write-format "(E14.6)" 1.6d-19)      "  0.160000E-18")
      (check "E16.6E3 / 1.6e-119" (write-format "(E16.6E3)" 1.6d-119)   "   0.160000E-118")
      (check "E10.4 too narrow"   (write-format "(E10.4)" 1.234d100)    "0.1234+101")
      ;; ES format
      (check "ES12.4 / 3.14159"   (write-format "(ES12.4)" 3.14159d0)   "  3.1416E+00")
      (check "ES12.4 / 1234.5"    (write-format "(ES12.4)" 1234.5d0)    "  1.2345E+03")
      (check "ES12.4 / 0.0001234" (write-format "(ES12.4)" 0.0001234d0) "  1.2340E-04")
      (check "ES12.4 / 0.0"       (write-format "(ES12.4)" 0.0d0)       "  0.0000E+00")
      ;; EN format
      (check "EN15.4 / 3.14159"   (write-format "(EN15.4)" 3.14159d0)   "     3.1416E+00")
      (check "EN15.4 / 1234.5"    (write-format "(EN15.4)" 1234.5d0)    "     1.2345E+03")
      (check "EN15.4 / 12345.6"   (write-format "(EN15.4)" 12345.6d0)   "    12.3456E+03")
      (check "EN15.4 / 1234567.8" (write-format "(EN15.4)" 1234567.8d0) "     1.2346E+06")
      (check "EN15.4 / 0.001234"  (write-format "(EN15.4)" 0.001234d0)  "     1.2340E-03")
      (check "EN15.4 / 0.0"       (write-format "(EN15.4)" 0.0d0)       "     0.0000E+00")
      ;; G format
      (check "G12.4 / 3.14159"    (write-format "(G12.4)" 3.14159d0)    "   3.142    ")
      (check "G12.4 / 0.00314"    (write-format "(G12.4)" 0.00314d0)    "  0.3140E-02")
      (check "G12.4 / 314159.0"   (write-format "(G12.4)" 314159.0d0)   "  0.3142E+06")
      ;; Note: this test expects CL's round-half-away-from-zero
      ;; behavior, which differs from gfortran's round-half-to-even
      ;; (banker's rounding) on exact tie cases. gfortran would give
      ;; "   1234.    ".
      (check "G12.4 / 1234.5 (CL rounding)"
             (write-format "(G12.4)" 1234.5d0)     "   1235.    ")
      (check "G12.4 / 0.0"        (write-format "(G12.4)" 0.0d0)        "   0.000    ")

      (format t "===== FLOAT EDGE CASES (vs gfortran) =====~%~%")
      (check "F6.3 / 99.9995 (no round-up tie)"
             (write-format "(F6.3)" 99.9995d0)   "99.999")
      (check "F8.3 / -0.0 (negative zero)"
             (write-format "(F8.3)" -0.0d0)      "  -0.000")
      (check "F6.3 / 0.9995 (carry from 0.999->1.000)"
             (write-format "(F6.3)" 0.9995d0)    " 1.000")
      (check "E10.3 / 0.0001"
             (write-format "(E10.3)" 0.0001d0)   " 0.100E-03")
      (check "F6.2 / 1e-10 (underflow to 0)"
             (write-format "(F6.2)" 1.0d-10)     "  0.00")
      (check "F6.0 / 1e10 (overflow)"
             (write-format "(F6.0)" 1.0d10)      "******")
      (check "ES10.2 / 0.0"
             (write-format "(ES10.2)" 0.0d0)     "  0.00E+00")

      (format t "~%~D failure(s)~%" failures)
      (zerop failures))))
