      SUBROUTINE SCALE1 ( XMIN, XMAX, N, XMINP, XMAXP, DIST )

c*********************************************************************72
c
cc SCALE1
c
C  ANSI FORTRAN
C  GIVEN XMIN, XMAX AND N, SCALE1 FINDS A NEW RANGE XMINP AND
C  XMAXP DIVISIBLE INTO APPROXIMATELY N LINEAR INTERVALS
C  OF SIZE DIST.
C  VINT IS AN ARRAY OF ACCEPTABLE VALUES FOR DIST (TIMES
C  AN INTEGER POWER OF 10).
C  SQR IS AN ARRAY OF GEOMETRIC MEANS OF ADJACENT VALUES
C  OF VINT.  IT IS USED AS BREAK POINTS TO DETERMINE
C  WHICH VINT VALUE TO ASSIGN TO DIST.
c
      DIMENSION VINT(4), SQR(3)
      DATA VINT(1), VINT(2), VINT(3), VINT(4) / 1., 2., 5., 10. /
      DATA SQR(1), SQR(2), SQR(3) / 1.414214, 3.162278, 7.071068 /
c
C  CHECK WHETHER PROPER INPUT VALUES WERE SUPPLIED.
c
      IF ( XMIN .LT. XMAX .AND. N .GT. 0 ) GO TO 10
      WRITE ( 6, 99999 )
99999 FORMAT ( 34H IMPROPER INPUT SUPPLIED TO SCALE1 )
      RETURN
c
C  DEL ACCOUNTS FOR COMPUTER ROUND-OFF.
C  DEL SHOULD BE GREATER THAN THE ROUND-OFF EXPECTED FROM
C  A DIVISION AND FLOAT OPERATION.  IT SHOULD BE LESS THAN
C  THE MINIMUM INCREMENT OF THE PLOTTING DEVICE USED BY
C  THE MAIN PROGRAM (IN.) DIVIDED BY THE PLOT SIZE (IN.)
C  TIMES NUMBER OF INTERVALS N.
c
10    DEL = .00002
      FN = N
c
C  FIND APPROXIMATE INTERVAL SIZE A.
c
      A = ( XMAX - XMIN ) / FN
      AL = ALOG10 ( A )
      NAL = AL
      IF ( A .LT. 1. ) NAL = NAL - 1
c
C  A IS SCALED INTO VARIABLE NAMED B BETWEEN 1 AND 10.
c
      B = A / 10.**NAL
c
C  THE CLOSEST PERMISSIBLE VALUE FOR B IS FOUND.
c
      DO 20 I = 1, 3
        IF ( B .LT. SQR ( I ) ) GO TO 30
20    CONTINUE
      I = 4
c
C  THE INTERVAL SIZE IS COMPUTED.
c
30    DIST = VINT(I) * 10.**NAL
      FM1 = XMIN / DIST
      M1 = FM1
      IF ( FM1 .LT. 0. ) M1 = M1 - 1
      IF ( ABS ( FLOAT ( M1 ) + 1. - FM1 ) .LT. DEL ) M1 = M1 + 1
c
C  THE NEW MINIMUM AND MAXIMUM LIMITS ARE FOUND.
c
      XMINP = DIST * FLOAT ( M1 )
      FM2 = XMAX / DIST
      M2 = FM2 + 1.
      IF ( FM2 .LT. ( -1. ) ) M2 = M2 - 1
      IF ( ABS ( FM2 + 1. - FLOAT ( M2 ) ) .LT. DEL ) M2 = M2 - 1
      XMAXP = DIST * FLOAT ( M2 )
c
C  ADJUST LIMITS TO ACCOUNT FOR ROUND-OFF IF NECESSARY.
c
      IF ( XMINP .GT. XMIN ) XMINP = XMIN
      IF ( XMAXP .LT. XMAX ) XMAXP = XMAX
      RETURN
      END
