;;;; b-ed-input-1.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; b-ed-input-1.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.

(in-package #:fortran-format)

(defparameter *b-ed-input-1-expected-failures* '())

(dolist (name *b-ed-input-1-expected-failures*)
  (pushnew name rt:*expected-failures*))
