;;;; d-ed-input-1.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; d-ed-input-1.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.
;;;;
;;;; 22 baseline failures, all signed-zero cases.  See
;;;; the F input expected-failures comment for the full account;
;;;; in short: gfortran's writeback suppresses the sign of zero,
;;;; CL (correctly, per IEEE) preserves it.  This is a corpus
;;;; artifact, not a bug in read-real.

(in-package #:fortran-format)

(defparameter *d-ed-input-1-expected-failures*
  ;; clisp doesn't support IEEE signed zero, so -0.0d0 reads to the
  ;; same object as 0.0d0; the corpus's expected 0.0d0 matches and
  ;; these tests pass cleanly on clisp.  On every other implementation
  ;; the sign is preserved and EQUAL distinguishes -0.0 from 0.0,
  ;; tripping the comparison.
  #+clisp '()
  #-clisp
  '(
    FMT.CORPUS.D-ED-INPUT-1.0104
    FMT.CORPUS.D-ED-INPUT-1.0106
    FMT.CORPUS.D-ED-INPUT-1.0108
    FMT.CORPUS.D-ED-INPUT-1.0135
    FMT.CORPUS.D-ED-INPUT-1.0137
    FMT.CORPUS.D-ED-INPUT-1.0249
    FMT.CORPUS.D-ED-INPUT-1.0251
    FMT.CORPUS.D-ED-INPUT-1.0253
    FMT.CORPUS.D-ED-INPUT-1.0280
    FMT.CORPUS.D-ED-INPUT-1.0282
    FMT.CORPUS.D-ED-INPUT-1.0365
    FMT.CORPUS.D-ED-INPUT-1.0367
    FMT.CORPUS.D-ED-INPUT-1.0369
    FMT.CORPUS.D-ED-INPUT-1.0396
    FMT.CORPUS.D-ED-INPUT-1.0398
    FMT.CORPUS.D-ED-INPUT-1.0452
    FMT.CORPUS.D-ED-INPUT-1.0454
    FMT.CORPUS.D-ED-INPUT-1.0456
    FMT.CORPUS.D-ED-INPUT-1.0483
    FMT.CORPUS.D-ED-INPUT-1.0485
    FMT.CORPUS.D-ED-INPUT-1.0541
    FMT.CORPUS.D-ED-INPUT-1.0543
   ))

(dolist (name *d-ed-input-1-expected-failures*)
  (pushnew name rt:*expected-failures*))
