;;;; f-ed-input-1.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; f-ed-input-1.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.
;;;;
;;;; 27 baseline failures, all signed-zero cases like
;;;; (F4.0) "-0.01" or (F5.1) "-0.001".  The input has a negative
;;;; sign and a magnitude that rounds to zero within the field.
;;;; CL preserves the sign through its float reader, giving
;;;; -0.0d0.  Fortran's IEEE arithmetic supports signed zero too,
;;;; and ifort writes -0.0 back unchanged; but gfortran's write
;;;; suppresses the sign on zero, so the corpus -- being a gfortran
;;;; writeback -- has 0.0 as the expected value.  Both -0.0d0 and
;;;; 0.0d0 satisfy =, but EQUAL distinguishes them, so the test
;;;; fails.  This is a corpus/comparison artifact, not a bug in
;;;; our reader.

(in-package #:fortran-format)

(defparameter *f-ed-input-1-expected-failures*
  ;; clisp doesn't support IEEE signed zero, so -0.0d0 reads to the
  ;; same object as 0.0d0; the corpus's expected 0.0d0 matches and
  ;; these tests pass cleanly on clisp.  On every other implementation
  ;; the sign is preserved and EQUAL distinguishes -0.0 from 0.0,
  ;; tripping the comparison.
  #+clisp '()
  #-clisp
  '(
    FMT.CORPUS.F-ED-INPUT-1.0107
    FMT.CORPUS.F-ED-INPUT-1.0109
    FMT.CORPUS.F-ED-INPUT-1.0111
    FMT.CORPUS.F-ED-INPUT-1.0139
    FMT.CORPUS.F-ED-INPUT-1.0141
    FMT.CORPUS.F-ED-INPUT-1.0287
    FMT.CORPUS.F-ED-INPUT-1.0289
    FMT.CORPUS.F-ED-INPUT-1.0291
    FMT.CORPUS.F-ED-INPUT-1.0319
    FMT.CORPUS.F-ED-INPUT-1.0321
    FMT.CORPUS.F-ED-INPUT-1.0437
    FMT.CORPUS.F-ED-INPUT-1.0439
    FMT.CORPUS.F-ED-INPUT-1.0441
    FMT.CORPUS.F-ED-INPUT-1.0469
    FMT.CORPUS.F-ED-INPUT-1.0471
    FMT.CORPUS.F-ED-INPUT-1.0557
    FMT.CORPUS.F-ED-INPUT-1.0559
    FMT.CORPUS.F-ED-INPUT-1.0561
    FMT.CORPUS.F-ED-INPUT-1.0589
    FMT.CORPUS.F-ED-INPUT-1.0591
    FMT.CORPUS.F-ED-INPUT-1.0647
    FMT.CORPUS.F-ED-INPUT-1.0649
    FMT.CORPUS.F-ED-INPUT-1.0651
    FMT.CORPUS.F-ED-INPUT-1.0679
    FMT.CORPUS.F-ED-INPUT-1.0681
    FMT.CORPUS.F-ED-INPUT-1.0739
    FMT.CORPUS.F-ED-INPUT-1.0741
   ))

(dolist (name *f-ed-input-1-expected-failures*)
  (pushnew name rt:*expected-failures*))
