;;;; f-ed-input-1.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; f-ed-input-1.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.
;;;;
;;;; 44 baseline failures.  Three categories surface:
;;;;
;;;;   1. Width truncation with embedded exponent.  e.g.
;;;;      (F2.0) "1e12" -- the input "1e12" doesn't fit in width 2,
;;;;      so the field as read should be "1e" which is not a valid
;;;;      Fortran real; gfortran errors.  We currently parse the
;;;;      partial as 1.0 instead.
;;;;
;;;;   2. Signed zero.  (F4.0) "-0.01" reads to 0 in gfortran (the
;;;;      negation is on a non-significant magnitude); CL preserves
;;;;      the sign giving -0.0d0, which is not EQUAL to 0.0d0 even
;;;;      though they're numerically =.
;;;;
;;;;   3. D-exponent within a narrow field.  (F4.0) "0.1D+200" --
;;;;      field 4 chars sees "0.1D" which truncates the exponent;
;;;;      gfortran errors.  We accept the truncated form as 0.1.
;;;;
;;;; Will be addressed in a separate change.

(in-package #:fortran-format)

(defparameter *f-ed-input-1-expected-failures*
  '(
    FMT.CORPUS.F-ED-INPUT-1.0055
    FMT.CORPUS.F-ED-INPUT-1.0056
    FMT.CORPUS.F-ED-INPUT-1.0107
    FMT.CORPUS.F-ED-INPUT-1.0109
    FMT.CORPUS.F-ED-INPUT-1.0111
    FMT.CORPUS.F-ED-INPUT-1.0120
    FMT.CORPUS.F-ED-INPUT-1.0139
    FMT.CORPUS.F-ED-INPUT-1.0141
    FMT.CORPUS.F-ED-INPUT-1.0150
    FMT.CORPUS.F-ED-INPUT-1.0235
    FMT.CORPUS.F-ED-INPUT-1.0236
    FMT.CORPUS.F-ED-INPUT-1.0287
    FMT.CORPUS.F-ED-INPUT-1.0289
    FMT.CORPUS.F-ED-INPUT-1.0291
    FMT.CORPUS.F-ED-INPUT-1.0300
    FMT.CORPUS.F-ED-INPUT-1.0319
    FMT.CORPUS.F-ED-INPUT-1.0321
    FMT.CORPUS.F-ED-INPUT-1.0330
    FMT.CORPUS.F-ED-INPUT-1.0385
    FMT.CORPUS.F-ED-INPUT-1.0386
    FMT.CORPUS.F-ED-INPUT-1.0437
    FMT.CORPUS.F-ED-INPUT-1.0439
    FMT.CORPUS.F-ED-INPUT-1.0441
    FMT.CORPUS.F-ED-INPUT-1.0450
    FMT.CORPUS.F-ED-INPUT-1.0469
    FMT.CORPUS.F-ED-INPUT-1.0471
    FMT.CORPUS.F-ED-INPUT-1.0480
    FMT.CORPUS.F-ED-INPUT-1.0557
    FMT.CORPUS.F-ED-INPUT-1.0559
    FMT.CORPUS.F-ED-INPUT-1.0561
    FMT.CORPUS.F-ED-INPUT-1.0570
    FMT.CORPUS.F-ED-INPUT-1.0589
    FMT.CORPUS.F-ED-INPUT-1.0591
    FMT.CORPUS.F-ED-INPUT-1.0600
    FMT.CORPUS.F-ED-INPUT-1.0647
    FMT.CORPUS.F-ED-INPUT-1.0649
    FMT.CORPUS.F-ED-INPUT-1.0651
    FMT.CORPUS.F-ED-INPUT-1.0660
    FMT.CORPUS.F-ED-INPUT-1.0679
    FMT.CORPUS.F-ED-INPUT-1.0681
    FMT.CORPUS.F-ED-INPUT-1.0690
    FMT.CORPUS.F-ED-INPUT-1.0739
    FMT.CORPUS.F-ED-INPUT-1.0741
    FMT.CORPUS.F-ED-INPUT-1.0750
   ))

(dolist (name *f-ed-input-1-expected-failures*)
  (pushnew name rt:*expected-failures*))
