;;;; o-ed-input-2.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; o-ed-input-2.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.

(in-package #:fortran-format)

(defparameter *o-ed-input-2-expected-failures* '())

(dolist (name *o-ed-input-2-expected-failures*)
  (pushnew name rt:*expected-failures*))
