;;;; a-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; a-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.  Implementation-specific failures should be
;;;; wrapped in #+<impl> / #-<impl>.

(in-package #:fortran-format)

(defparameter *a-ed-expected-failures*
  '())

(dolist (name *a-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
