;;;; colon-f-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; colon-f-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.
;;;;
;;;; The 1 failure is the same gfortran single-precision
;;;; corpus-data artifact as standalone f-ed-output.0128: (F10.0)
;;;; 123456789 -> "123456792." because gfortran coerced the integer
;;;; literal to single-precision where the nearest representable
;;;; value is exactly 123456792.  Colon is a no-op when values are
;;;; available, so this just inherits.

(in-package #:fortran-format)

(defparameter *colon-f-ed-expected-failures*
  '(
    FMT.CORPUS.COLON-F-ED-OUTPUT.0128
   ))

(dolist (name *colon-f-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
