;;;; colon-g-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; colon-g-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.

(in-package #:fortran-format)

(defparameter *colon-g-ed-expected-failures* '())

(dolist (name *colon-g-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
