;;;; d-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; d-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.

(in-package #:fortran-format)

;;; --- SBCL ----------------------------------------------------
#+sbcl
(defparameter *d-ed-expected-failures* '())

;;; --- CMUCL ---------------------------------------------------
#+cmu
(defparameter *d-ed-expected-failures* '())

(dolist (name *d-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
