;;;; e-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from e-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.
;;;;
;;;; All entries are wrapped in #+<impl> blocks.  Each implementation's
;;;; section is maintained independently -- fixing a bug for one
;;;; implementation only requires editing that implementation's block.
;;;; A failure that's currently universal will appear in every section;
;;;; that's intentional and easier to manage than trying to maintain
;;;; a separate "common" section.
;;;;
;;;; SBCL: 0 failures.
;;;; CMUCL: 0 failures.

(in-package #:fortran-format)

;;; --- SBCL ----------------------------------------------------
#+sbcl
(defparameter *e-ed-expected-failures* '())

;;; --- CMUCL ---------------------------------------------------
#+cmu
(defparameter *e-ed-expected-failures* '())

(dolist (name *e-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
