;;;; en-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; en-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.
;;;;
;;;; SBCL: 26 failures.  All (ENw.d) or (ENw.dEe) of integer
;;;;   values at decade boundaries -- format-en's raw-exp uses
;;;;   (floor (log mag 10d0)), which on SBCL returns one ulp low at
;;;;   power-of-10 inputs ((log 1d3 10d0) -> 2.9999999999999996d0),
;;;;   giving raw-exp = 2 instead of 3 and shifting the value to
;;;;   the wrong engineering decade.  Will be addressed in a
;;;;   separate change.
;;;; CMUCL: expected 0 failures.  CMUCL widens log args internally,
;;;;   so (log 1d3 10d0) returns 3.0d0 exactly.

(in-package #:fortran-format)

;;; --- SBCL ----------------------------------------------------
#+sbcl
(defparameter *en-ed-expected-failures*
  '(
    FMT.CORPUS.EN-ED-OUTPUT.0122
    FMT.CORPUS.EN-ED-OUTPUT.0123
    FMT.CORPUS.EN-ED-OUTPUT.0237
    FMT.CORPUS.EN-ED-OUTPUT.0238
    FMT.CORPUS.EN-ED-OUTPUT.0329
    FMT.CORPUS.EN-ED-OUTPUT.0330
    FMT.CORPUS.EN-ED-OUTPUT.0398
    FMT.CORPUS.EN-ED-OUTPUT.0605
    FMT.CORPUS.EN-ED-OUTPUT.0606
    FMT.CORPUS.EN-ED-OUTPUT.0620
    FMT.CORPUS.EN-ED-OUTPUT.0720
    FMT.CORPUS.EN-ED-OUTPUT.0721
    FMT.CORPUS.EN-ED-OUTPUT.0812
    FMT.CORPUS.EN-ED-OUTPUT.0813
    FMT.CORPUS.EN-ED-OUTPUT.0881
    FMT.CORPUS.EN-ED-OUTPUT.0882
    FMT.CORPUS.EN-ED-OUTPUT.0927
    FMT.CORPUS.EN-ED-OUTPUT.1088
    FMT.CORPUS.EN-ED-OUTPUT.1089
    FMT.CORPUS.EN-ED-OUTPUT.1203
    FMT.CORPUS.EN-ED-OUTPUT.1204
    FMT.CORPUS.EN-ED-OUTPUT.1295
    FMT.CORPUS.EN-ED-OUTPUT.1571
    FMT.CORPUS.EN-ED-OUTPUT.1572
    FMT.CORPUS.EN-ED-OUTPUT.1686
    FMT.CORPUS.EN-ED-OUTPUT.2054
   ))

;;; --- CMUCL ---------------------------------------------------
#+cmu
(defparameter *en-ed-expected-failures*
  '(
    FMT.CORPUS.EN-ED-OUTPUT.0620
   ))


;;; --- Other implementations -----------------------------------
#-(or sbcl cmu)
(defparameter *en-ed-expected-failures* '())

(dolist (name *en-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
