;;;; f-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; f-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.  Implementation-specific failures should be
;;;; wrapped in #+<impl> / #-<impl>.
;;;;
;;;; 1 failure (down from 46 baseline; leading-zero suppression
;;;; and Fw.0 round-to-zero fixed).
;;;;
;;;; FMT.CORPUS.F-ED-OUTPUT.0128 is a corpus-data artifact, not an
;;;; implementation defect.  The test asks (write-format "(F10.0)"
;;;; 123456789) to produce "123456792.".  gfortran's runtime printed
;;;; 123456792 because its compiler coerced the integer literal
;;;; 123456789 to single-precision, where the nearest representable
;;;; value is exactly 123456792, and then its print routine emits
;;;; every digit of the binary value.  CMUCL's ~F prints just enough
;;;; digits to read back the same float and so emits "123456790."
;;;; even after coercion to single-float; SBCL behaves similarly.
;;;; Matching gfortran would require bypassing CL's ~F and writing
;;;; our own digit-expansion routine, which is not worthwhile for
;;;; one corpus entry.

(in-package #:fortran-format)

(defparameter *f-ed-expected-failures*
  '(FMT.CORPUS.F-ED-OUTPUT.0128))

(dolist (name *f-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
