;;;; g-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; g-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.

(in-package #:fortran-format)

(defparameter *g-ed-expected-failures*
  #+sbcl
  '(
    )
  #+cmu
  '(
    )
  #-(or sbcl cmu)
  '())

(dolist (name *g-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
