;;;; i-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; i-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.  Implementation-specific failures should be
;;;; wrapped in #+<impl> / #-<impl>.
;;;;
;;;; 0 failures.  All 336 baseline failures fixed: 30 by the
;;;; Iw.0-of-0 fix, 306 by the F95 12.2.2 implicit-colon fix.

(in-package #:fortran-format)

(defparameter *i-ed-expected-failures*
  '())

(dolist (name *i-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
