;;;; slash-f-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; slash-f-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.
;;;;
;;;; Same gfortran single-precision artifact as f-ed-output.0128
;;;; and colon-f-ed-output.0128: (F10.0) 123456789 -> "123456792."

(in-package #:fortran-format)

(defparameter *slash-f-ed-expected-failures*
  '(
    FMT.CORPUS.SLASH-F-ED-OUTPUT.0128
   ))

(dolist (name *slash-f-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
