;;;; sp-en-ed-output.expected-failures.lisp
;;;;
;;;; Known failures for the deftests generated from
;;;; sp-en-ed-output.test.
;;;;
;;;; Initially auto-generated by
;;;;   (fortran-format::establish-baseline-expected-failures ...)
;;;; but maintained by hand thereafter: remove a name when its
;;;; bug is fixed.
;;;;
;;;; SBCL: 21 failures.  Rounding-tie cases where SBCL's
;;;;   half-to-even ~E rounding lands differently than gfortran.
;;;; CMUCL: 1 failures.  CMUCL's half-away-from-zero
;;;;   matches gfortran on most of these.

(in-package #:fortran-format)

;;; --- SBCL ----------------------------------------------------
#+sbcl
(defparameter *sp-en-ed-expected-failures*
  '(
    FMT.CORPUS.SP-EN-ED-OUTPUT.0122
    FMT.CORPUS.SP-EN-ED-OUTPUT.0123
    FMT.CORPUS.SP-EN-ED-OUTPUT.0237
    FMT.CORPUS.SP-EN-ED-OUTPUT.0238
    FMT.CORPUS.SP-EN-ED-OUTPUT.0329
    FMT.CORPUS.SP-EN-ED-OUTPUT.0330
    FMT.CORPUS.SP-EN-ED-OUTPUT.0605
    FMT.CORPUS.SP-EN-ED-OUTPUT.0606
    FMT.CORPUS.SP-EN-ED-OUTPUT.0620
    FMT.CORPUS.SP-EN-ED-OUTPUT.0720
    FMT.CORPUS.SP-EN-ED-OUTPUT.0721
    FMT.CORPUS.SP-EN-ED-OUTPUT.0812
    FMT.CORPUS.SP-EN-ED-OUTPUT.0813
    FMT.CORPUS.SP-EN-ED-OUTPUT.0881
    FMT.CORPUS.SP-EN-ED-OUTPUT.0882
    FMT.CORPUS.SP-EN-ED-OUTPUT.1088
    FMT.CORPUS.SP-EN-ED-OUTPUT.1089
    FMT.CORPUS.SP-EN-ED-OUTPUT.1203
    FMT.CORPUS.SP-EN-ED-OUTPUT.1204
    FMT.CORPUS.SP-EN-ED-OUTPUT.1571
    FMT.CORPUS.SP-EN-ED-OUTPUT.1572
   ))

;;; --- CMUCL ---------------------------------------------------
#+cmu
(defparameter *sp-en-ed-expected-failures*
  '(
    FMT.CORPUS.SP-EN-ED-OUTPUT.0620
   ))

(dolist (name *sp-en-ed-expected-failures*)
  (pushnew name rt:*expected-failures*))
